- name: Deploy Docker app to EC2 instances
  hosts: webservers
  become: yes
  vars:
    docker_user: shinobisar
    docker_password: "{{ lookup('env', 'DOCKER_PASS') }}"
  tasks:
    - name: Ensure Docker is installed
      apt: { name: docker.io, state: present }
    - name: Add user to docker group
      user: { name: ubuntu, groups: docker, append: yes }
    - name: Log in to Docker Hub
      docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
    - name: Pull and run Docker container
      docker_container:
        name: my-app-container
        image: "{{ docker_user }}/my-app:{{ docker_tag }}"
        state: started
        restart_policy: always
        ports: "80:80"